# Generated by Django 5.2.16 on 2026-07-28 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_lineitem_min_validators'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='pdf',
            field=models.FileField(blank=True, upload_to='invoices/%Y/%m/'),
        ),
    ]
