# Generated by Django 5.2.16 on 2026-07-28 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='currency',
            field=models.CharField(choices=[('GHS', 'Ghanaian Cedi (GH₵)'), ('NGN', 'Nigerian Naira (₦)'), ('USD', 'US Dollar ($)')], default='GHS', max_length=3),
        ),
        migrations.AddField(
            model_name='invoice',
            name='currency',
            field=models.CharField(choices=[('GHS', 'Ghanaian Cedi (GH₵)'), ('NGN', 'Nigerian Naira (₦)'), ('USD', 'US Dollar ($)')], default='GHS', max_length=3),
        ),
    ]
