# Generated by Django 5.2.16 on 2026-07-28 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_client_unique_client_email_per_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='number',
            field=models.CharField(editable=False, max_length=20),
        ),
    ]
